/**
 * Full 500-topic queue for The Faith Wound cron engine.
 * Topics are consumed in order. Already-published slugs are skipped.
 */
export const ARTICLE_TOPICS = [
  // RELIGIOUS TRAUMA CORE
  { title: 'What Is Religious Trauma? The Clinical Definition', category: 'religious-trauma', tags: ['religious-trauma', 'clinical', 'definition'] },
  { title: "Marlene Winell's Religious Trauma Syndrome: The Symptoms", category: 'religious-trauma', tags: ['religious-trauma', 'symptoms', 'rts'] },
  { title: 'The Difference Between Religious Trauma and Normal Faith Doubt', category: 'religious-trauma', tags: ['religious-trauma', 'faith-doubt'] },
  { title: 'Religious Trauma and PTSD: The Clinical Overlap', category: 'religious-trauma', tags: ['ptsd', 'religious-trauma', 'clinical'] },
  { title: 'What Helps in Religious Trauma Recovery: The Evidence', category: 'healing', tags: ['recovery', 'religious-trauma', 'evidence'] },
  { title: 'Religious Trauma and Shame: The Entanglement', category: 'religious-trauma', tags: ['shame', 'religious-trauma', 'healing'] },
  { title: 'The Neuroscience of Religious Trauma: What Happens in the Brain', category: 'religious-trauma', tags: ['neuroscience', 'brain', 'religious-trauma'] },
  { title: 'Complex PTSD and Religious Upbringing: The Connection', category: 'healing', tags: ['cptsd', 'religious-trauma', 'childhood'] },
  { title: 'Religious Trauma in Childhood: The Long-Term Effects', category: 'religious-trauma', tags: ['childhood', 'religious-trauma', 'long-term'] },
  { title: 'How Religious Trauma Affects Your Nervous System', category: 'somatic-healing', tags: ['nervous-system', 'religious-trauma', 'somatic'] },
  // DECONSTRUCTION
  { title: "What Deconstruction Actually Is (And What It Isn't)", category: 'deconstruction', tags: ['deconstruction', 'faith', 'leaving-religion'] },
  { title: "Brian McLaren's Approach: Faith After Doubt, Not Faith vs. Doubt", category: 'deconstruction', tags: ['faith-doubt', 'deconstruction'] },
  { title: 'The Deconstruction Community: What It Offers and Its Limits', category: 'deconstruction', tags: ['deconstruction', 'community', 'support'] },
  { title: 'The Six Stages of Faith Deconstruction', category: 'deconstruction', tags: ['stages', 'deconstruction', 'faith'] },
  { title: 'Deconstruction vs. Apostasy: Why the Distinction Matters', category: 'deconstruction', tags: ['deconstruction', 'apostasy'] },
  { title: 'When Deconstruction Becomes Reconstruction', category: 'deconstruction', tags: ['reconstruction', 'deconstruction', 'identity'] },
  { title: 'The Intellectual Phase of Deconstruction: Reading Your Way Out', category: 'deconstruction', tags: ['intellectual', 'deconstruction', 'books'] },
  { title: 'Deconstruction and Mental Health: What the Research Shows', category: 'deconstruction', tags: ['mental-health', 'deconstruction', 'research'] },
  { title: 'Progressive Christianity as a Stopping Point in Deconstruction', category: 'deconstruction', tags: ['progressive-christianity', 'deconstruction'] },
  { title: 'How Long Does Deconstruction Take?', category: 'deconstruction', tags: ['deconstruction', 'timeline', 'process'] },
  // LEAVING CHURCH
  { title: 'Leaving Evangelical Christianity: The Specific Challenges', category: 'leaving-church', tags: ['evangelical', 'leaving-church', 'identity'] },
  { title: 'Leaving Catholicism: Confession, Guilt, and Identity', category: 'leaving-church', tags: ['catholicism', 'guilt', 'identity'] },
  { title: 'Leaving High-Control Religious Groups: The Cult Spectrum', category: 'high-control-groups', tags: ['cults', 'high-control', 'leaving-religion'] },
  { title: "Leaving Jehovah's Witnesses: The Shunning and After", category: 'leaving-church', tags: ['jehovahs-witnesses', 'shunning', 'leaving-religion'] },
  { title: 'Leaving Mormonism: What Makes It Different', category: 'leaving-church', tags: ['mormonism', 'lds', 'leaving-religion'] },
  { title: 'Leaving Islam: The Cultural and Spiritual Complexity', category: 'leaving-church', tags: ['islam', 'leaving-religion', 'cultural'] },
  { title: 'Leaving Orthodox Judaism: Community, Law, and Identity', category: 'leaving-church', tags: ['orthodox-judaism', 'leaving-religion', 'community'] },
  { title: 'Leaving Pentecostalism: The Gifts, the Pressure, the Aftermath', category: 'leaving-church', tags: ['pentecostalism', 'leaving-church', 'healing'] },
  { title: 'Leaving the Southern Baptist Convention: What Survivors Say', category: 'leaving-church', tags: ['southern-baptist', 'leaving-church', 'survivors'] },
  { title: 'Leaving a Megachurch: The Scale of the Loss', category: 'leaving-church', tags: ['megachurch', 'leaving-church', 'community-loss'] },
  // PURITY CULTURE
  { title: 'Purity Culture Wounds: What the Research Shows', category: 'purity-culture', tags: ['purity-culture', 'shame', 'sexuality', 'research'] },
  { title: 'Sex, Shame, and the Body After Purity Culture', category: 'purity-culture', tags: ['sexuality', 'shame', 'purity-culture', 'body'] },
  { title: 'The Recovery from Christian Purity Culture', category: 'purity-culture', tags: ['purity-culture', 'christianity', 'recovery'] },
  { title: 'How Purity Culture Affects Marriages', category: 'purity-culture', tags: ['purity-culture', 'marriage', 'sexuality'] },
  { title: 'The I Kissed Dating Goodbye Generation: Where Are They Now?', category: 'purity-culture', tags: ['purity-culture', 'dating', 'generation'] },
  { title: 'Reclaiming Your Body After Purity Culture', category: 'purity-culture', tags: ['body', 'purity-culture', 'reclaiming'] },
  { title: 'Purity Culture and Eating Disorders: The Hidden Connection', category: 'purity-culture', tags: ['purity-culture', 'eating-disorders', 'body'] },
  { title: 'Purity Culture and LGBTQ+ Youth: The Compounded Harm', category: 'lgbtq-faith', tags: ['lgbtq', 'purity-culture', 'youth'] },
  { title: 'What Dianna Anderson Gets Right About Damaged Goods', category: 'purity-culture', tags: ['damaged-goods', 'purity-culture', 'recovery'] },
  { title: 'Purity Culture and Sexual Dysfunction: What Therapists See', category: 'purity-culture', tags: ['purity-culture', 'sexual-dysfunction', 'therapy'] },
  // GRIEF AND LOSS
  { title: "The Grief of Leaving: What You're Actually Mourning", category: 'grief', tags: ['grief', 'leaving-religion', 'loss'] },
  { title: 'Grief Groups for People Leaving Religion: How to Find Them', category: 'grief', tags: ['grief', 'community', 'support-groups'] },
  { title: 'The Five Losses of Leaving Religion', category: 'grief', tags: ['grief', 'loss', 'leaving-religion'] },
  { title: "Disenfranchised Grief: Why Nobody Validates Your Faith Loss", category: 'grief', tags: ['disenfranchised-grief', 'faith-loss', 'validation'] },
  { title: 'Grieving the God You Believed In', category: 'grief', tags: ['grief', 'god', 'belief', 'loss'] },
  { title: 'The Grief of Losing Your Religious Community', category: 'grief', tags: ['grief', 'community', 'loss'] },
  { title: 'How Long Does the Grief of Leaving Religion Last?', category: 'grief', tags: ['grief', 'timeline', 'leaving-religion'] },
  { title: 'Complicated Grief After Religious Trauma', category: 'grief', tags: ['complicated-grief', 'religious-trauma', 'therapy'] },
  { title: 'Grieving Your Former Self: The Identity Loss After Faith', category: 'grief', tags: ['grief', 'identity', 'self', 'faith-loss'] },
  { title: 'When Grief Turns to Relief: The Complicated Emotions of Leaving', category: 'grief', tags: ['grief', 'relief', 'leaving-religion'] },
  // IDENTITY
  { title: 'Integration: Who Are You Now That the Framework Is Gone?', category: 'identity', tags: ['identity', 'integration', 'post-faith'] },
  { title: 'Atheism, Agnosticism, and the Space Between', category: 'identity', tags: ['atheism', 'agnosticism', 'post-faith'] },
  { title: 'Rebuilding Your Value System After Religion', category: 'identity', tags: ['values', 'identity', 'post-faith', 'rebuilding'] },
  { title: 'The Existential Crisis of Leaving Religion', category: 'identity', tags: ['existential', 'crisis', 'leaving-religion'] },
  { title: 'Finding Meaning Without God: What Actually Works', category: 'identity', tags: ['meaning', 'secular', 'post-faith', 'purpose'] },
  { title: 'Who Am I Without My Religion? Rebuilding Identity', category: 'identity', tags: ['identity', 'religion', 'rebuilding'] },
  { title: 'Secular Ethics: How to Build a Moral Framework Without Religion', category: 'identity', tags: ['ethics', 'secular', 'moral-framework'] },
  { title: 'The Impostor Syndrome of Leaving Religion', category: 'identity', tags: ['impostor-syndrome', 'leaving-religion', 'identity'] },
  { title: 'Coming Out as Non-Religious to Your Family', category: 'identity', tags: ['non-religious', 'family', 'coming-out'] },
  { title: 'Post-Faith Identity: The Research on Who Thrives', category: 'identity', tags: ['post-faith', 'identity', 'research'] },
  // RELATIONSHIPS
  { title: "When Your Family Is Still In: How to Navigate It", category: 'healing', tags: ['family', 'relationships', 'leaving-religion'] },
  { title: "Religious Trauma and Relationships: Who Understands, Who Doesn't", category: 'healing', tags: ['relationships', 'religious-trauma', 'understanding'] },
  { title: 'Marriage Across the Faith Divide: What Helps', category: 'healing', tags: ['marriage', 'faith-divide', 'relationships'] },
  { title: 'Divorce After Deconstruction: The Spiritual and Legal Tangle', category: 'healing', tags: ['divorce', 'deconstruction', 'relationships'] },
  { title: 'Friendships After Leaving Religion: Who Stays, Who Goes', category: 'healing', tags: ['friendships', 'leaving-religion', 'community'] },
  { title: "When Your Spouse Won't Deconstruct With You", category: 'healing', tags: ['spouse', 'deconstruction', 'marriage'] },
  { title: 'Parenting Across the Faith Divide', category: 'healing', tags: ['parenting', 'faith-divide', 'children'] },
  { title: 'How to Talk to Your Kids About Why You Left', category: 'healing', tags: ['parenting', 'children', 'leaving-religion'] },
  { title: 'The Loneliness of Leaving Religion', category: 'healing', tags: ['loneliness', 'leaving-religion', 'community'] },
  // THERAPY AND HEALING
  { title: 'Finding a Therapist Who Gets Religious Trauma', category: 'therapy', tags: ['therapy', 'religious-trauma', 'finding-help'] },
  { title: 'EMDR for Religious Trauma: Does It Work?', category: 'therapy', tags: ['emdr', 'religious-trauma', 'therapy'] },
  { title: 'IFS (Internal Family Systems) and Religious Trauma', category: 'therapy', tags: ['ifs', 'internal-family-systems', 'religious-trauma'] },
  { title: 'Somatic Therapy for Religious Trauma: The Body Keeps the Score', category: 'somatic-healing', tags: ['somatic', 'therapy', 'religious-trauma', 'body'] },
  { title: 'CBT for Religious OCD: What Works', category: 'therapy', tags: ['cbt', 'religious-ocd', 'therapy'] },
  { title: 'Narrative Therapy for Reconstructing Your Story After Religion', category: 'therapy', tags: ['narrative-therapy', 'reconstruction', 'story'] },
  { title: 'Online Therapy for Religious Trauma: What to Look For', category: 'therapy', tags: ['online-therapy', 'religious-trauma', 'finding-help'] },
  { title: 'Group Therapy for Religious Trauma Survivors', category: 'therapy', tags: ['group-therapy', 'religious-trauma', 'community'] },
  { title: 'The Therapeutic Alliance When Your Therapist Is Religious', category: 'therapy', tags: ['therapeutic-alliance', 'therapist', 'religion'] },
  { title: 'What to Tell Your Therapist About Your Religious Background', category: 'therapy', tags: ['therapy', 'religious-background', 'communication'] },
  // BODY AND SOMATIC
  { title: 'The Body After Religious Trauma: What to Expect', category: 'somatic-healing', tags: ['body', 'religious-trauma', 'somatic', 'healing'] },
  { title: 'Yoga and Religious Trauma: Reclaiming the Body Without Triggering', category: 'somatic-healing', tags: ['yoga', 'religious-trauma', 'body', 'healing'] },
  { title: 'Somatic Experiencing for Religious Trauma Recovery', category: 'somatic-healing', tags: ['somatic-experiencing', 'religious-trauma', 'recovery'] },
  { title: 'Breathwork for Nervous System Regulation After Religious Trauma', category: 'somatic-healing', tags: ['breathwork', 'nervous-system', 'religious-trauma'] },
  { title: 'Sleep Problems After Religious Trauma: What Helps', category: 'sleep', tags: ['sleep', 'religious-trauma', 'healing'] },
  { title: 'Chronic Pain and Religious Trauma: The Somatic Connection', category: 'somatic-healing', tags: ['chronic-pain', 'religious-trauma', 'somatic'] },
  { title: 'Exercise and Religious Trauma Recovery: The Evidence', category: 'somatic-healing', tags: ['exercise', 'religious-trauma', 'recovery'] },
  { title: 'Eating and Body Image After Religious Trauma', category: 'somatic-healing', tags: ['eating', 'body-image', 'religious-trauma'] },
  { title: 'Sexuality After Religious Trauma: Reclaiming Pleasure', category: 'somatic-healing', tags: ['sexuality', 'religious-trauma', 'pleasure', 'healing'] },
  { title: 'Mindfulness for Religious Trauma Survivors: Navigating the Triggers', category: 'somatic-healing', tags: ['mindfulness', 'religious-trauma', 'triggers'] },
  // LGBTQ+ AND FAITH
  { title: 'LGBTQ+ Religious Trauma: The Compounded Harm', category: 'lgbtq-faith', tags: ['lgbtq', 'religious-trauma', 'harm'] },
  { title: 'Conversion Therapy Survivors: The Long Road to Healing', category: 'lgbtq-faith', tags: ['conversion-therapy', 'survivors', 'healing'] },
  { title: 'Queer Theology: What It Offers and Its Limits', category: 'lgbtq-faith', tags: ['queer-theology', 'lgbtq', 'faith'] },
  { title: 'Coming Out in a Religious Family: Survival Guide', category: 'lgbtq-faith', tags: ['coming-out', 'religious-family', 'lgbtq'] },
  { title: 'Affirming Churches: What to Look For and What to Watch Out For', category: 'lgbtq-faith', tags: ['affirming-churches', 'lgbtq', 'faith'] },
  { title: 'Bisexual Erasure in Religious Communities', category: 'lgbtq-faith', tags: ['bisexual', 'erasure', 'religious-communities'] },
  { title: 'Transgender Faith Journeys: The Specific Wounds', category: 'lgbtq-faith', tags: ['transgender', 'faith', 'religious-trauma'] },
  { title: 'Non-Binary Identity and Religious Trauma', category: 'lgbtq-faith', tags: ['non-binary', 'identity', 'religious-trauma'] },
  { title: 'LGBTQ+ Grief After Leaving Religion', category: 'lgbtq-faith', tags: ['lgbtq', 'grief', 'leaving-religion'] },
  { title: 'Finding LGBTQ+ Community After Leaving Religion', category: 'lgbtq-faith', tags: ['lgbtq', 'community', 'leaving-religion'] },
  // HIGH-CONTROL GROUPS
  { title: 'The BITE Model: How Cults Control Behavior, Information, Thought, and Emotion', category: 'high-control-groups', tags: ['bite-model', 'cults', 'control'] },
  { title: 'Spiritual Abuse: The Clinical Definition and Signs', category: 'high-control-groups', tags: ['spiritual-abuse', 'clinical', 'signs'] },
  { title: 'Narcissistic Pastors and Church Leaders: The Pattern', category: 'high-control-groups', tags: ['narcissistic', 'pastors', 'church-leaders'] },
  { title: 'Thought-Stopping Techniques in Religious Settings', category: 'high-control-groups', tags: ['thought-stopping', 'religious', 'control'] },
  { title: 'Shunning and Excommunication: The Psychological Impact', category: 'high-control-groups', tags: ['shunning', 'excommunication', 'psychological'] },
  { title: 'The Stages of Cult Recovery', category: 'high-control-groups', tags: ['cult', 'recovery', 'stages'] },
  { title: 'Love Bombing in Religious Communities', category: 'high-control-groups', tags: ['love-bombing', 'religious', 'manipulation'] },
  { title: 'Financial Exploitation in Religious Settings', category: 'high-control-groups', tags: ['financial', 'exploitation', 'religious'] },
  { title: 'Spiritual Bypassing: When Religion Avoids Real Healing', category: 'high-control-groups', tags: ['spiritual-bypassing', 'religion', 'healing'] },
  { title: 'Recovery from a Charismatic Leader: The Specific Challenges', category: 'high-control-groups', tags: ['charismatic-leader', 'recovery', 'challenges'] },
  // SECULAR COMMUNITY AND MEANING
  { title: 'Sunday Assembly and Secular Community: What It Offers', category: 'secular-community', tags: ['sunday-assembly', 'secular', 'community'] },
  { title: 'Secular Humanism as a Post-Faith Framework', category: 'secular-spirituality', tags: ['secular-humanism', 'post-faith', 'framework'] },
  { title: 'Finding Ritual Without Religion', category: 'secular-spirituality', tags: ['ritual', 'secular', 'meaning'] },
  { title: 'Secular Grief Rituals: Marking Loss Without God', category: 'secular-spirituality', tags: ['grief', 'ritual', 'secular'] },
  { title: 'Philosophy as a Replacement for Religion: What Works', category: 'secular-spirituality', tags: ['philosophy', 'religion', 'replacement'] },
  { title: 'Stoicism for Religious Trauma Survivors', category: 'secular-spirituality', tags: ['stoicism', 'religious-trauma', 'philosophy'] },
  { title: 'Buddhism for Former Christians: What Translates', category: 'secular-spirituality', tags: ['buddhism', 'christianity', 'post-faith'] },
  { title: 'Nature-Based Spirituality After Religion', category: 'secular-spirituality', tags: ['nature', 'spirituality', 'post-faith'] },
  { title: 'Volunteering and Service as Post-Faith Meaning', category: 'secular-community', tags: ['volunteering', 'service', 'meaning', 'post-faith'] },
  { title: 'Online Communities for Ex-Religious People: The Best Options', category: 'secular-community', tags: ['online-communities', 'ex-religious', 'support'] },
  // OCD AND SCRUPULOSITY
  { title: 'Religious OCD (Scrupulosity): The Clinical Picture', category: 'ocd-scrupulosity', tags: ['religious-ocd', 'scrupulosity', 'clinical'] },
  { title: 'ERP for Scrupulosity: The Gold Standard Treatment', category: 'ocd-scrupulosity', tags: ['erp', 'scrupulosity', 'treatment'] },
  { title: 'The Difference Between Genuine Faith and OCD Scrupulosity', category: 'ocd-scrupulosity', tags: ['faith', 'ocd', 'scrupulosity', 'difference'] },
  { title: 'Scrupulosity in Childhood: What Parents Need to Know', category: 'ocd-scrupulosity', tags: ['scrupulosity', 'childhood', 'parents'] },
  { title: 'When Religion Makes OCD Worse: The Reassurance Trap', category: 'ocd-scrupulosity', tags: ['ocd', 'religion', 'reassurance', 'trap'] },
  { title: 'Intrusive Religious Thoughts: What They Mean and What They Don\'t', category: 'ocd-scrupulosity', tags: ['intrusive-thoughts', 'religious', 'ocd'] },
  { title: 'Confession Compulsions in Religious OCD', category: 'ocd-scrupulosity', tags: ['confession', 'compulsions', 'religious-ocd'] },
  { title: 'Fear of Hell and OCD: Untangling the Knot', category: 'ocd-scrupulosity', tags: ['fear-of-hell', 'ocd', 'scrupulosity'] },
  { title: 'Medication for Religious OCD: What the Research Shows', category: 'ocd-scrupulosity', tags: ['medication', 'religious-ocd', 'research'] },
  { title: 'Recovery Stories: Life After Scrupulosity', category: 'ocd-scrupulosity', tags: ['recovery', 'scrupulosity', 'stories'] },
  // ANGER AND ADVOCACY
  { title: 'The Anger Phase of Religious Trauma Recovery', category: 'healing', tags: ['anger', 'religious-trauma', 'recovery'] },
  { title: 'When Anger at Religion Becomes Consuming', category: 'healing', tags: ['anger', 'religion', 'consuming', 'healing'] },
  { title: 'Religious Trauma Advocacy: How to Channel Your Story', category: 'healing', tags: ['advocacy', 'religious-trauma', 'story'] },
  { title: 'Writing Your Way Through Religious Trauma', category: 'healing', tags: ['writing', 'religious-trauma', 'healing'] },
  { title: 'The Role of Humor in Religious Trauma Recovery', category: 'healing', tags: ['humor', 'religious-trauma', 'recovery'] },
  { title: 'Podcasts for Religious Trauma Recovery: The Best Ones', category: 'healing', tags: ['podcasts', 'religious-trauma', 'recovery'] },
  { title: 'Books That Help After Religious Trauma', category: 'healing', tags: ['books', 'religious-trauma', 'recovery'] },
  { title: 'Documentaries About Religious Trauma and Cults', category: 'healing', tags: ['documentaries', 'religious-trauma', 'cults'] },
  { title: 'The Ex-Vangelical Movement: What It Is and What It Offers', category: 'healing', tags: ['exvangelical', 'movement', 'community'] },
  { title: 'Religious Trauma and Political Deconstruction', category: 'healing', tags: ['religious-trauma', 'political', 'deconstruction'] },
  // ADDITIONAL TOPICS 141-200
  { title: 'The 7 Stages of Faith Deconstruction (And Where You Are)', category: 'deconstruction', tags: ['stages', 'deconstruction', 'faith', 'process'] },
  { title: 'Religious Trauma and Anxiety: The Overlap', category: 'religious-trauma', tags: ['anxiety', 'religious-trauma', 'overlap'] },
  { title: 'Religious Trauma and Depression: What the Research Shows', category: 'religious-trauma', tags: ['depression', 'religious-trauma', 'research'] },
  { title: 'Hypervigilance After Religious Trauma', category: 'religious-trauma', tags: ['hypervigilance', 'religious-trauma', 'nervous-system'] },
  { title: 'The Fawn Response in Religious Settings', category: 'religious-trauma', tags: ['fawn-response', 'religious', 'trauma'] },
  { title: 'People-Pleasing and Religious Upbringing', category: 'religious-trauma', tags: ['people-pleasing', 'religious', 'upbringing'] },
  { title: 'Perfectionism After Religious Trauma', category: 'religious-trauma', tags: ['perfectionism', 'religious-trauma', 'healing'] },
  { title: 'Black-and-White Thinking After Religious Trauma', category: 'religious-trauma', tags: ['black-and-white', 'thinking', 'religious-trauma'] },
  { title: 'Catastrophizing and Religious Upbringing', category: 'religious-trauma', tags: ['catastrophizing', 'religious', 'upbringing'] },
  { title: 'The Inner Critic After Religious Trauma', category: 'religious-trauma', tags: ['inner-critic', 'religious-trauma', 'healing'] },
  { title: 'Self-Compassion After Religious Shame', category: 'healing', tags: ['self-compassion', 'shame', 'religious-trauma'] },
  { title: 'Forgiveness After Religious Trauma: Is It Required?', category: 'healing', tags: ['forgiveness', 'religious-trauma', 'healing'] },
  { title: 'The Difference Between Forgiveness and Reconciliation', category: 'healing', tags: ['forgiveness', 'reconciliation', 'healing'] },
  { title: 'Trust After Religious Trauma: Rebuilding Slowly', category: 'healing', tags: ['trust', 'religious-trauma', 'rebuilding'] },
  { title: 'Vulnerability After Religious Trauma', category: 'healing', tags: ['vulnerability', 'religious-trauma', 'healing'] },
  { title: 'Shame Resilience After Religious Trauma', category: 'healing', tags: ['shame', 'resilience', 'religious-trauma'] },
  { title: 'The Role of Creativity in Religious Trauma Recovery', category: 'healing', tags: ['creativity', 'religious-trauma', 'recovery'] },
  { title: 'Art Therapy for Religious Trauma Survivors', category: 'therapy', tags: ['art-therapy', 'religious-trauma', 'healing'] },
  { title: 'Music and Religious Trauma: Reclaiming What Was Weaponized', category: 'healing', tags: ['music', 'religious-trauma', 'reclaiming'] },
  { title: 'The Holidays After Leaving Religion', category: 'healing', tags: ['holidays', 'leaving-religion', 'family'] },
  // 161-200
  { title: 'Christmas After Leaving Christianity', category: 'healing', tags: ['christmas', 'leaving-christianity', 'holidays'] },
  { title: 'Easter After Leaving Christianity', category: 'healing', tags: ['easter', 'leaving-christianity', 'holidays'] },
  { title: 'Ramadan After Leaving Islam', category: 'leaving-church', tags: ['ramadan', 'leaving-islam', 'holidays'] },
  { title: 'Passover After Leaving Judaism', category: 'leaving-church', tags: ['passover', 'leaving-judaism', 'holidays'] },
  { title: 'Religious Trauma and Suicidal Ideation: What to Know', category: 'religious-trauma', tags: ['suicidal-ideation', 'religious-trauma', 'crisis'] },
  { title: 'Crisis Resources for Religious Trauma Survivors', category: 'healing', tags: ['crisis', 'resources', 'religious-trauma'] },
  { title: 'The Spiritual Emergency: When Deconstruction Becomes a Crisis', category: 'deconstruction', tags: ['spiritual-emergency', 'deconstruction', 'crisis'] },
  { title: 'Hospitalization and Religious Trauma: Navigating the System', category: 'healing', tags: ['hospitalization', 'religious-trauma', 'system'] },
  { title: 'Medication and Religious Trauma Recovery', category: 'healing', tags: ['medication', 'religious-trauma', 'recovery'] },
  { title: 'Psychiatric Diagnosis After Religious Trauma', category: 'healing', tags: ['psychiatric', 'diagnosis', 'religious-trauma'] },
  { title: 'The Overlap Between Religious Trauma and Dissociation', category: 'religious-trauma', tags: ['dissociation', 'religious-trauma', 'overlap'] },
  { title: 'Dissociative Identity Disorder and Religious Abuse', category: 'religious-trauma', tags: ['did', 'religious-abuse', 'dissociation'] },
  { title: 'Attachment Theory and Religious Trauma', category: 'religious-trauma', tags: ['attachment', 'religious-trauma', 'theory'] },
  { title: 'Anxious Attachment and Religious Upbringing', category: 'religious-trauma', tags: ['anxious-attachment', 'religious', 'upbringing'] },
  { title: 'Avoidant Attachment and Religious Trauma', category: 'religious-trauma', tags: ['avoidant-attachment', 'religious-trauma'] },
  { title: 'Secure Attachment After Religious Trauma: Is It Possible?', category: 'healing', tags: ['secure-attachment', 'religious-trauma', 'healing'] },
  { title: 'The Window of Tolerance After Religious Trauma', category: 'healing', tags: ['window-of-tolerance', 'religious-trauma', 'healing'] },
  { title: 'Polyvagal Theory and Religious Trauma Recovery', category: 'somatic-healing', tags: ['polyvagal', 'religious-trauma', 'recovery'] },
  { title: 'The Freeze Response and Religious Trauma', category: 'somatic-healing', tags: ['freeze-response', 'religious-trauma', 'somatic'] },
  { title: 'Fight-or-Flight and Religious Settings', category: 'somatic-healing', tags: ['fight-or-flight', 'religious', 'somatic'] },
  // 201-250
  { title: 'Triggers After Religious Trauma: How to Work With Them', category: 'healing', tags: ['triggers', 'religious-trauma', 'healing'] },
  { title: 'Church Triggers: When Sacred Music Becomes Distressing', category: 'healing', tags: ['church', 'triggers', 'music', 'distressing'] },
  { title: 'Smell and Religious Trauma: The Sensory Triggers', category: 'somatic-healing', tags: ['smell', 'sensory', 'religious-trauma', 'triggers'] },
  { title: 'Grounding Techniques for Religious Trauma Survivors', category: 'somatic-healing', tags: ['grounding', 'religious-trauma', 'techniques'] },
  { title: 'The Safe Place Visualization for Religious Trauma', category: 'somatic-healing', tags: ['visualization', 'religious-trauma', 'healing'] },
  { title: 'Journaling Prompts for Religious Trauma Recovery', category: 'healing', tags: ['journaling', 'religious-trauma', 'prompts'] },
  { title: 'The 5-4-3-2-1 Grounding Technique for Religious Trauma', category: 'somatic-healing', tags: ['grounding', '5-4-3-2-1', 'religious-trauma'] },
  { title: 'Tapping (EFT) for Religious Trauma', category: 'somatic-healing', tags: ['tapping', 'eft', 'religious-trauma'] },
  { title: 'Cold Water Therapy for Nervous System Regulation', category: 'somatic-healing', tags: ['cold-water', 'nervous-system', 'regulation'] },
  { title: 'The Vagus Nerve and Religious Trauma Recovery', category: 'somatic-healing', tags: ['vagus-nerve', 'religious-trauma', 'recovery'] },
  { title: 'Sleep Hygiene for Religious Trauma Survivors', category: 'sleep', tags: ['sleep-hygiene', 'religious-trauma', 'survivors'] },
  { title: 'Nightmares After Religious Trauma: What They Mean', category: 'sleep', tags: ['nightmares', 'religious-trauma', 'sleep'] },
  { title: 'Insomnia and Religious Trauma: The Connection', category: 'sleep', tags: ['insomnia', 'religious-trauma', 'sleep'] },
  { title: 'The Role of Dreams in Religious Trauma Processing', category: 'sleep', tags: ['dreams', 'religious-trauma', 'processing'] },
  { title: 'Nutrition and Religious Trauma Recovery', category: 'somatic-healing', tags: ['nutrition', 'religious-trauma', 'recovery'] },
  { title: 'The Gut-Brain Connection and Religious Trauma', category: 'somatic-healing', tags: ['gut-brain', 'religious-trauma', 'somatic'] },
  { title: 'Inflammation and Chronic Stress After Religious Trauma', category: 'somatic-healing', tags: ['inflammation', 'chronic-stress', 'religious-trauma'] },
  { title: 'The Immune System and Religious Trauma', category: 'somatic-healing', tags: ['immune-system', 'religious-trauma', 'somatic'] },
  { title: 'Chronic Fatigue After Religious Trauma', category: 'somatic-healing', tags: ['chronic-fatigue', 'religious-trauma', 'somatic'] },
  { title: 'Fibromyalgia and Religious Trauma: The Research', category: 'somatic-healing', tags: ['fibromyalgia', 'religious-trauma', 'research'] },
  // 251-300
  { title: 'Autoimmune Conditions and Religious Trauma', category: 'somatic-healing', tags: ['autoimmune', 'religious-trauma', 'somatic'] },
  { title: 'The Nervous System Reset After Religious Trauma', category: 'somatic-healing', tags: ['nervous-system', 'reset', 'religious-trauma'] },
  { title: 'Acupuncture for Religious Trauma Recovery', category: 'somatic-healing', tags: ['acupuncture', 'religious-trauma', 'recovery'] },
  { title: 'Massage Therapy for Religious Trauma Survivors', category: 'somatic-healing', tags: ['massage', 'religious-trauma', 'body'] },
  { title: 'Dance Movement Therapy for Religious Trauma', category: 'somatic-healing', tags: ['dance', 'movement', 'religious-trauma'] },
  { title: 'Qigong for Religious Trauma Recovery', category: 'somatic-healing', tags: ['qigong', 'religious-trauma', 'recovery'] },
  { title: 'Tai Chi for Religious Trauma Survivors', category: 'somatic-healing', tags: ['tai-chi', 'religious-trauma', 'somatic'] },
  { title: 'Swimming and Water for Religious Trauma Recovery', category: 'somatic-healing', tags: ['swimming', 'water', 'religious-trauma'] },
  { title: 'Running and Religious Trauma: The Meditative Effect', category: 'somatic-healing', tags: ['running', 'religious-trauma', 'meditation'] },
  { title: 'Strength Training After Religious Trauma: Reclaiming Agency', category: 'somatic-healing', tags: ['strength-training', 'religious-trauma', 'agency'] },
  { title: 'The Spiritual Bypassing Trap in New Age Communities', category: 'secular-spirituality', tags: ['spiritual-bypassing', 'new-age', 'trap'] },
  { title: 'Astrology and Post-Faith Meaning-Making', category: 'secular-spirituality', tags: ['astrology', 'post-faith', 'meaning'] },
  { title: 'Tarot as a Secular Tool for Self-Reflection', category: 'secular-spirituality', tags: ['tarot', 'secular', 'self-reflection'] },
  { title: 'Paganism After Christianity: What Draws People', category: 'secular-spirituality', tags: ['paganism', 'christianity', 'post-faith'] },
  { title: 'Unitarian Universalism as a Soft Landing After Religion', category: 'secular-community', tags: ['unitarian-universalism', 'soft-landing', 'religion'] },
  { title: 'Ethical Culture Societies: A Secular Community Option', category: 'secular-community', tags: ['ethical-culture', 'secular', 'community'] },
  { title: 'Humanist Celebrants: Secular Ceremonies for Life Events', category: 'secular-community', tags: ['humanist', 'celebrants', 'secular', 'ceremonies'] },
  { title: 'The Secular Meditation Movement: What It Offers', category: 'secular-spirituality', tags: ['secular', 'meditation', 'mindfulness'] },
  { title: 'Secular Grief Support: What Exists and What Is Missing', category: 'secular-community', tags: ['secular', 'grief', 'support'] },
  { title: 'Building Secular Community from Scratch', category: 'secular-community', tags: ['secular', 'community', 'building'] },
  // 301-350
  { title: 'The Ex-Muslim Experience: Specific Challenges and Resources', category: 'leaving-church', tags: ['ex-muslim', 'experience', 'resources'] },
  { title: 'The Ex-Mormon Experience: Specific Challenges and Resources', category: 'leaving-church', tags: ['ex-mormon', 'experience', 'resources'] },
  { title: 'The Ex-Jehovah\'s Witness Experience: Specific Challenges', category: 'leaving-church', tags: ['ex-jw', 'experience', 'challenges'] },
  { title: 'The Ex-Catholic Experience: Guilt, Ritual, and Identity', category: 'leaving-church', tags: ['ex-catholic', 'guilt', 'ritual', 'identity'] },
  { title: 'The Ex-Evangelical Experience: What Makes It Unique', category: 'leaving-church', tags: ['ex-evangelical', 'experience', 'unique'] },
  { title: 'The Ex-Orthodox Jewish Experience', category: 'leaving-church', tags: ['ex-orthodox', 'jewish', 'experience'] },
  { title: 'The Ex-Fundamentalist Experience: Leaving the Strictest Forms', category: 'leaving-church', tags: ['ex-fundamentalist', 'experience', 'leaving'] },
  { title: 'The Ex-Charismatic Experience: Prophecy, Tongues, and After', category: 'leaving-church', tags: ['ex-charismatic', 'prophecy', 'tongues'] },
  { title: 'The Ex-Quiverfull Experience: Leaving Large-Family Culture', category: 'leaving-church', tags: ['ex-quiverfull', 'large-family', 'culture'] },
  { title: 'The Ex-Scientology Experience: What Makes It Different', category: 'high-control-groups', tags: ['ex-scientology', 'experience', 'different'] },
  { title: 'Religious Trauma and Race: The Intersection', category: 'religious-trauma', tags: ['race', 'religious-trauma', 'intersection'] },
  { title: 'Black Church Trauma: The Specific Wounds', category: 'religious-trauma', tags: ['black-church', 'trauma', 'specific'] },
  { title: 'Latino/a Religious Trauma: Catholicism, Culture, and Family', category: 'religious-trauma', tags: ['latino', 'religious-trauma', 'catholicism'] },
  { title: 'Asian American Religious Trauma: The Cultural Overlay', category: 'religious-trauma', tags: ['asian-american', 'religious-trauma', 'cultural'] },
  { title: 'Indigenous Religious Trauma: Colonialism and Forced Conversion', category: 'religious-trauma', tags: ['indigenous', 'religious-trauma', 'colonialism'] },
  { title: 'Religious Trauma and Disability: The Compounded Experience', category: 'religious-trauma', tags: ['disability', 'religious-trauma', 'compounded'] },
  { title: 'Religious Trauma and Neurodivergence: ADHD, Autism, and Faith', category: 'religious-trauma', tags: ['neurodivergence', 'adhd', 'autism', 'faith'] },
  { title: 'Religious Trauma and Chronic Illness: The Spiritual Dimension', category: 'religious-trauma', tags: ['chronic-illness', 'religious-trauma', 'spiritual'] },
  { title: 'Religious Trauma and Poverty: The Economic Dimension', category: 'religious-trauma', tags: ['poverty', 'religious-trauma', 'economic'] },
  { title: 'Religious Trauma and Gender: The Patriarchy Wound', category: 'religious-trauma', tags: ['gender', 'religious-trauma', 'patriarchy'] },
  // 351-400
  { title: 'Women and Religious Trauma: The Specific Wounds', category: 'religious-trauma', tags: ['women', 'religious-trauma', 'specific'] },
  { title: 'Men and Religious Trauma: The Wounds That Go Unspoken', category: 'religious-trauma', tags: ['men', 'religious-trauma', 'unspoken'] },
  { title: 'Religious Trauma in Adolescence: The Critical Period', category: 'religious-trauma', tags: ['adolescence', 'religious-trauma', 'critical'] },
  { title: 'Religious Trauma in College: The Deconversion Moment', category: 'religious-trauma', tags: ['college', 'religious-trauma', 'deconversion'] },
  { title: 'Religious Trauma in Midlife: The Late Awakening', category: 'religious-trauma', tags: ['midlife', 'religious-trauma', 'awakening'] },
  { title: 'Religious Trauma in Later Life: Leaving at 60+', category: 'religious-trauma', tags: ['later-life', 'religious-trauma', 'leaving'] },
  { title: 'Intergenerational Religious Trauma: Breaking the Cycle', category: 'religious-trauma', tags: ['intergenerational', 'religious-trauma', 'cycle'] },
  { title: 'Religious Trauma and Parenting: Not Passing It On', category: 'religious-trauma', tags: ['parenting', 'religious-trauma', 'cycle'] },
  { title: 'Raising Children Without Religion: The Research', category: 'healing', tags: ['children', 'without-religion', 'research'] },
  { title: 'Secular Parenting: Building Ethics Without God', category: 'healing', tags: ['secular-parenting', 'ethics', 'children'] },
  { title: 'The Prodigal Narrative: How Religion Frames Your Return', category: 'religious-trauma', tags: ['prodigal', 'narrative', 'religion', 'return'] },
  { title: 'Religious Manipulation Tactics: Recognizing Them', category: 'high-control-groups', tags: ['manipulation', 'religious', 'tactics'] },
  { title: 'Gaslighting in Religious Settings', category: 'high-control-groups', tags: ['gaslighting', 'religious', 'settings'] },
  { title: 'DARVO in Religious Communities', category: 'high-control-groups', tags: ['darvo', 'religious', 'communities'] },
  { title: 'The Sunk Cost Fallacy in Religious Commitment', category: 'high-control-groups', tags: ['sunk-cost', 'religious', 'commitment'] },
  { title: 'Cognitive Dissonance and Religious Belief', category: 'deconstruction', tags: ['cognitive-dissonance', 'religious', 'belief'] },
  { title: 'The Backfire Effect in Religious Deconstruction', category: 'deconstruction', tags: ['backfire-effect', 'religious', 'deconstruction'] },
  { title: 'Confirmation Bias and Religious Belief', category: 'deconstruction', tags: ['confirmation-bias', 'religious', 'belief'] },
  { title: 'The Psychology of Belief: Why We Believe What We Believe', category: 'deconstruction', tags: ['psychology', 'belief', 'why'] },
  { title: 'Motivated Reasoning in Religious Contexts', category: 'deconstruction', tags: ['motivated-reasoning', 'religious', 'contexts'] },
  // 401-500
  { title: 'The Role of Community in Religious Belief Maintenance', category: 'deconstruction', tags: ['community', 'religious', 'belief'] },
  { title: 'Social Identity Theory and Religious Groups', category: 'deconstruction', tags: ['social-identity', 'religious', 'groups'] },
  { title: 'Terror Management Theory and Religious Belief', category: 'deconstruction', tags: ['terror-management', 'religious', 'belief'] },
  { title: 'The Existential Function of Religion', category: 'deconstruction', tags: ['existential', 'function', 'religion'] },
  { title: 'Meaning-Making After the Loss of Religious Certainty', category: 'identity', tags: ['meaning-making', 'religious', 'certainty'] },
  { title: 'Post-Traumatic Growth After Religious Trauma', category: 'healing', tags: ['post-traumatic-growth', 'religious-trauma', 'growth'] },
  { title: 'Resilience After Religious Trauma: What the Research Shows', category: 'healing', tags: ['resilience', 'religious-trauma', 'research'] },
  { title: 'The Hero\'s Journey and Religious Deconstruction', category: 'deconstruction', tags: ['heros-journey', 'deconstruction', 'narrative'] },
  { title: 'Narrative Identity and Religious Trauma', category: 'identity', tags: ['narrative-identity', 'religious-trauma', 'healing'] },
  { title: 'The Examined Life After Religion', category: 'identity', tags: ['examined-life', 'religion', 'philosophy'] },
  { title: 'Epistemic Humility After Religious Certainty', category: 'identity', tags: ['epistemic-humility', 'religious', 'certainty'] },
  { title: 'Wonder Without God: Secular Awe and Transcendence', category: 'secular-spirituality', tags: ['wonder', 'secular', 'awe', 'transcendence'] },
  { title: 'The Science of Awe and Its Role in Post-Faith Life', category: 'secular-spirituality', tags: ['awe', 'science', 'post-faith'] },
  { title: 'Gratitude Without God: Secular Practices That Work', category: 'secular-spirituality', tags: ['gratitude', 'secular', 'practices'] },
  { title: 'Compassion Practices After Religion', category: 'secular-spirituality', tags: ['compassion', 'practices', 'post-faith'] },
  { title: 'Loving-Kindness Meditation for Religious Trauma Survivors', category: 'somatic-healing', tags: ['loving-kindness', 'meditation', 'religious-trauma'] },
  { title: 'The Science of Meditation and Religious Trauma Recovery', category: 'somatic-healing', tags: ['meditation', 'science', 'religious-trauma'] },
  { title: 'Secular Mindfulness vs. Buddhist Mindfulness: The Difference', category: 'secular-spirituality', tags: ['secular-mindfulness', 'buddhist', 'difference'] },
  { title: 'The Default Mode Network and Religious Rumination', category: 'somatic-healing', tags: ['default-mode-network', 'religious', 'rumination'] },
  { title: 'Neuroplasticity and Religious Trauma Recovery', category: 'healing', tags: ['neuroplasticity', 'religious-trauma', 'recovery'] },
  { title: 'The Healing Timeline: What to Expect Year by Year', category: 'healing', tags: ['healing-timeline', 'religious-trauma', 'year-by-year'] },
  { title: 'Milestones in Religious Trauma Recovery', category: 'healing', tags: ['milestones', 'religious-trauma', 'recovery'] },
  { title: 'What Full Recovery from Religious Trauma Looks Like', category: 'healing', tags: ['full-recovery', 'religious-trauma', 'looks-like'] },
  { title: 'Life After Religious Trauma: Thriving Stories', category: 'healing', tags: ['life-after', 'religious-trauma', 'thriving'] },
  { title: 'The Gift of Leaving: What You Gain When You Go', category: 'healing', tags: ['gift-of-leaving', 'religious-trauma', 'gain'] },
  { title: 'Integrating Your Religious Past Without Being Defined by It', category: 'identity', tags: ['integrating', 'religious-past', 'identity'] },
  { title: 'The Both/And: Holding Complexity After Black-and-White Thinking', category: 'identity', tags: ['both-and', 'complexity', 'black-and-white'] },
  { title: 'Curiosity as a Post-Faith Superpower', category: 'identity', tags: ['curiosity', 'post-faith', 'superpower'] },
  { title: 'The Courage to Not Know: Embracing Uncertainty', category: 'identity', tags: ['courage', 'uncertainty', 'post-faith'] },
  { title: 'What You Keep: The Parts of Religion Worth Holding', category: 'identity', tags: ['what-you-keep', 'religion', 'worth-holding'] },
  { title: 'Religious Trauma and the Arts: Healing Through Expression', category: 'healing', tags: ['arts', 'religious-trauma', 'expression'] },
  { title: 'Memoir Writing After Religious Trauma', category: 'healing', tags: ['memoir', 'religious-trauma', 'writing'] },
  { title: 'Poetry and Religious Trauma: The Language of Survival', category: 'healing', tags: ['poetry', 'religious-trauma', 'language'] },
  { title: 'Film and Religious Trauma: Movies That Get It Right', category: 'healing', tags: ['film', 'religious-trauma', 'movies'] },
  { title: 'Religious Trauma in Literature: The Books That Understand', category: 'healing', tags: ['literature', 'religious-trauma', 'books'] },
  { title: 'The Future of Religious Trauma Research', category: 'religious-trauma', tags: ['future', 'research', 'religious-trauma'] },
  { title: 'Religious Trauma and Public Health: The Bigger Picture', category: 'religious-trauma', tags: ['public-health', 'religious-trauma', 'bigger-picture'] },
  { title: 'Advocacy for Religious Trauma Recognition in Mental Health', category: 'healing', tags: ['advocacy', 'recognition', 'mental-health'] },
  { title: 'The Spiritual but Not Religious: A Post-Faith Identity', category: 'secular-spirituality', tags: ['spiritual-not-religious', 'post-faith', 'identity'] },
  { title: 'Secular Solstice and Other Non-Religious Celebrations', category: 'secular-community', tags: ['secular-solstice', 'celebrations', 'non-religious'] },
  { title: 'The Philosophy of Secular Humanism: A Primer', category: 'secular-spirituality', tags: ['secular-humanism', 'philosophy', 'primer'] },
  { title: 'Existentialism for Religious Trauma Survivors', category: 'secular-spirituality', tags: ['existentialism', 'religious-trauma', 'survivors'] },
  { title: 'Camus and the Absurd: A Post-Faith Framework', category: 'secular-spirituality', tags: ['camus', 'absurd', 'post-faith'] },
  { title: 'Viktor Frankl and Meaning After Religious Trauma', category: 'secular-spirituality', tags: ['viktor-frankl', 'meaning', 'religious-trauma'] },
  { title: 'The Examined Life: Socrates and Post-Faith Living', category: 'secular-spirituality', tags: ['socrates', 'examined-life', 'post-faith'] },
  { title: 'Epicureanism and Post-Faith Pleasure', category: 'secular-spirituality', tags: ['epicureanism', 'post-faith', 'pleasure'] },
  { title: 'The Tao and Post-Faith Spirituality', category: 'secular-spirituality', tags: ['tao', 'post-faith', 'spirituality'] },
  { title: 'Zen and the Art of Post-Faith Living', category: 'secular-spirituality', tags: ['zen', 'post-faith', 'living'] },
  { title: 'The Science of Happiness After Religion', category: 'healing', tags: ['happiness', 'science', 'post-faith'] },
  { title: 'Positive Psychology and Religious Trauma Recovery', category: 'healing', tags: ['positive-psychology', 'religious-trauma', 'recovery'] },
  { title: 'Flow States and Post-Faith Meaning', category: 'healing', tags: ['flow-states', 'post-faith', 'meaning'] },
  { title: 'The Good Life Without God: Philosophical Perspectives', category: 'secular-spirituality', tags: ['good-life', 'without-god', 'philosophical'] },
  { title: 'Secular Rites of Passage: Marking Life Without Religion', category: 'secular-community', tags: ['secular-rites', 'passage', 'life'] },
  { title: 'Death Without Religion: Secular End-of-Life Perspectives', category: 'secular-spirituality', tags: ['death', 'secular', 'end-of-life'] },
  { title: 'Grief Without God: Secular Approaches to Loss', category: 'secular-spirituality', tags: ['grief', 'secular', 'loss'] },
  { title: 'The Secular Afterlife: What Non-Religious People Believe', category: 'secular-spirituality', tags: ['secular-afterlife', 'non-religious', 'belief'] },
  { title: 'Finding Your People After Religion', category: 'secular-community', tags: ['finding-people', 'post-religion', 'community'] },
  { title: 'Online Support for Religious Trauma: The Best Communities', category: 'secular-community', tags: ['online-support', 'religious-trauma', 'communities'] },
  { title: 'Reddit and Religious Trauma: The r/exvangelical Community', category: 'secular-community', tags: ['reddit', 'exvangelical', 'community'] },
  { title: 'The Clergy Project: Support for Former Religious Leaders', category: 'secular-community', tags: ['clergy-project', 'former-leaders', 'support'] },
  { title: 'Recovery from Religion Foundation: What It Offers', category: 'secular-community', tags: ['recovery-from-religion', 'foundation', 'support'] },
];
